[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_30 = "3XymXN3tc11oMRpb7piYdGB7E8PdM9c3WhuNTfSvPKE8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jaspergabriel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
