[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_15 = "CVjaQEELRcQuUyayj5vbfNeYLx8CzipneabsgCVGsRJ1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jaspergabriel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
