[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_8 = "6eRfdYvgRemdkt6FxskGYS1MUpiHFPLsMFitZDcUft3y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jaspergabriel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
