[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_27 = "5eqvDv1dD11zR4EEaxE6uK3NscwfTDR9nh5KbNLWX4Cm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jaspergabriel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
