[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
other_program = "EW6R34TciFADwYMyWNeq5fQcpYsTd22Sf5GJKGES7Hnr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jaspergabriel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
