[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_14 = "H6WZr6wR3XoToy6AXTSUcm6bujHR5bsPoKRbnQg5s5D2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jaspergabriel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
